# Generated by Django 5.2.6 on 2025-09-15 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repositories', '0004_remove_repofile_has_map_repository_has_map'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc', models.IntegerField(blank=True, null=True)),
                ('vg', models.IntegerField(blank=True, null=True)),
                ('evg', models.IntegerField(blank=True, null=True)),
                ('ivg', models.IntegerField(blank=True, null=True)),
                ('n', models.IntegerField(blank=True, null=True)),
                ('uniq_op', models.IntegerField(blank=True, null=True)),
                ('uniq_opnd', models.IntegerField(blank=True, null=True)),
                ('total_op', models.IntegerField(blank=True, null=True)),
                ('total_opnd', models.IntegerField(blank=True, null=True)),
                ('v', models.FloatField(blank=True, null=True)),
                ('l', models.FloatField(blank=True, null=True)),
                ('d', models.FloatField(blank=True, null=True)),
                ('i', models.FloatField(blank=True, null=True)),
                ('e', models.FloatField(blank=True, null=True)),
                ('b', models.FloatField(blank=True, null=True)),
                ('t', models.FloatField(blank=True, null=True)),
                ('iocode', models.IntegerField(blank=True, null=True)),
                ('iocomment', models.IntegerField(blank=True, null=True)),
                ('ioblank', models.IntegerField(blank=True, null=True)),
                ('iocode_and_comment', models.IntegerField(blank=True, null=True)),
                ('branch_count', models.IntegerField(blank=True, null=True)),
                ('defects', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('repo_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='repositories.repofile')),
            ],
        ),
    ]
