services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: gitmap-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - db
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: gitmap
      DB_USERNAME: gitmap_user
      DB_PASSWORD: gitmap_pass

    command: php artisan serve --host=0.0.0.0 --port=8000

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: gitmap-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    command: npm start
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true

  db:
    image: postgres:15
    container_name: db
    restart: always
    environment:
      POSTGRES_DB: gitmap
      POSTGRES_USER: gitmap_user
      POSTGRES_PASSWORD: gitmap_pass
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - db

volumes:
  pg_data:
