# Generated by Django 5.2.6 on 2025-09-14 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repositories', '0002_remove_filecontent_updated_at_repository_pinned_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_edges', to='repositories.repository')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edge_sources', to='repositories.repofile')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edge_targets', to='repositories.repofile')),
            ],
        ),
        migrations.CreateModel(
            name='NodePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('repo_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='node_position', to='repositories.repofile')),
            ],
        ),
    ]
