# Generated by Django 5.2.5 on 2025-08-31 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepoFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=1024)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('parent_path', models.CharField(blank=True, max_length=1024, null=True)),
                ('extension', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.CharField(max_length=50)),
                ('sha', models.CharField(max_length=255)),
                ('size', models.PositiveIntegerField(blank=True, null=True)),
                ('is_binary', models.BooleanField(default=False)),
                ('is_indexed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('repo_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='repositories.repofile')),
            ],
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('branch', models.CharField(default='main', max_length=255)),
                ('default_branch', models.CharField(default='main', max_length=255)),
                ('is_watched', models.BooleanField(default=True)),
                ('is_indexed', models.BooleanField(default=False)),
                ('index_status', models.CharField(default='pending', max_length=50)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='users.user')),
            ],
        ),
        migrations.AddField(
            model_name='repofile',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='repositories.repository'),
        ),
    ]
