# Generated by Django 5.2.5 on 2025-08-31 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filecontent',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='repository',
            name='pinned_by',
            field=models.ManyToManyField(blank=True, related_name='pinned_repositories', to='users.user'),
        ),
        migrations.AlterField(
            model_name='filecontent',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='filecontent',
            name='repo_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repositories.repofile'),
        ),
        migrations.AlterField(
            model_name='repofile',
            name='extension',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='repofile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='repofile',
            name='parent_path',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='repofile',
            name='path',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='repofile',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repositories.repository'),
        ),
        migrations.AlterField(
            model_name='repofile',
            name='sha',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='repository',
            name='branch',
            field=models.CharField(default='main', max_length=100),
        ),
        migrations.AlterField(
            model_name='repository',
            name='default_branch',
            field=models.CharField(default='main', max_length=100),
        ),
        migrations.AlterField(
            model_name='repository',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='repository',
            name='url',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='repository',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.CreateModel(
            name='FileChunk',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chunk_index', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('repo_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repositories.repofile')),
            ],
        ),
        migrations.CreateModel(
            name='ChunkEmbedding',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('embedding', models.JSONField()),
                ('model_used', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chunk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='repositories.filechunk')),
            ],
        ),
    ]
