# Generated by Django 5.2.6 on 2025-09-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0002_remove_filecontent_updated_at_repository_pinned_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='repofile',
            name='has_map',
            field=models.BooleanField(default=False),
        ),
    ]
