# Generated by Django 5.2.6 on 2025-09-14 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0003_repofile_has_map'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repofile',
            name='has_map',
        ),
        migrations.AddField(
            model_name='repository',
            name='has_map',
            field=models.BooleanField(default=False),
        ),
    ]
