name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: gitmap
          POSTGRES_USER: gitmap_user
          POSTGRES_PASSWORD: gitmap_pass
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U gitmap_user -d gitmap"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

      redis:
        image: redis:7
        ports:
          - 6379:6379

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker
        run: docker compose version

      - name: Build containers
        run: docker compose build

      - name: Run migrations
        run: docker compose run --rm backend python manage.py migrate

      - name: Run tests
        run: docker compose run --rm backend python manage.py test -v 2
